site_name: MFractor Documentation
copyright: Copyright &copy; 2015-2019 <a href="https://www.mfractor.com">MFractor Pty Ltd</a>
site_author: "MFractor Pty Ltd"
site_description: "Documentation for MFractor, a powerful productivity tool for Visual Studio"
repo_url: "https://github.com/mfractor/mfractor.github.io"
remote_branch: "master"
google_analytics: ['UA-71910290-3', 'docs.mfractor.com']
strict: true
theme:
  name: 'material'
  logo: 'images/logo.svg'
  favicon: 'images/favicon.ico'
  palette:
    primary: 'blue'
extra:
  disqus: 'mfractor'
markdown_extensions:
  - attr_list

nav:
- Home: index.md
- Installation And Setup: installation-and-setup.md
- Visual Studio Windows: visual-studio-mac.md
- Visual Studio Mac: visual-studio-windows.md
- Licensing: licensing.md
- Support: support.md
- FAQ: faq.md
- Xamarin.Forms:
  - Overview: xamarin-forms/overview.md
  - Binding Context Resolution:
    - Overview: xamarin-forms/binding-context-resolution/overview.md
    - Automatic ViewModel Detection: xamarin-forms/binding-context-resolution/automatic-viewmodel-detection.md
    - BindingContext Evaluation: xamarin-forms/binding-context-resolution/binding-context-evaluation.md
    - DataTemplate Binding Context Resolution: xamarin-forms/binding-context-resolution/data-template-binding-context-resolution.md
    - Using The DesignTimeBindingContextAttribute: xamarin-forms/binding-context-resolution/design-time-binding-context-attribute.md
    - Cross Project Binding Context Resolution: xamarin-forms/binding-context-resolution/cross-project-binding-context-resolution.md
  - Working With ViewModels:
    - View-ViewModel Navigation: xamarin-forms/working-with-viewmodels/view-viewmodel-navigation.md
    - Data Binding IntelliSense: xamarin-forms/working-with-viewmodels/data-binding-intellisense.md
    - Data Binding Analysis: xamarin-forms/working-with-viewmodels/data-binding-analysis.md
    - Generating Properties/Commands: xamarin-forms/working-with-viewmodels/generating-properties-and-commands.md
    - MVVM Wizard: xamarin-forms/working-with-viewmodels/mvvm-wizard.md
  - Custom Controls:
    - Extracting Custom Controls: xamarin-forms/custom-controls/extracting-custom-controls.md
    - Bindable Property Wizard: xamarin-forms/custom-controls/bindable-property-wizard.md
- Image Management:
  - Overview: image-management/overview.md
  - Managing Images: image-management/managing-image-assets.md
  - Importing Images: image-management/importing-image-assets.md
  - Deleting Images: image-management/deleting-image-assets.md
  - Optimising Images: image-management/optimising-image-assets.md
- Utilities:
  - Delete Output Folders: utilities/delete-output-folders.md
  - Clean And Compress: utilities/clean-and-compress.md
- Release Notes:
  - Mac:
    - Current Release: release-notes/mac/current.md
    - v3:
      - v3.9: release-notes/mac/v3/v3.9.md
  - Windows:
    - Current Release: release-notes/windows/current.md
    - v0:
      - v0.1: release-notes/windows/v0/v0.1.md
- Legal:
  - Privacy Policy: legal/privacy-policy.pdf
  - End User License: legal/end-user-license.pdf
