site_name: mfractor docs
theme: readthedocs
copyright: Copyright &copy; 2016 <a href="https://www.mfractor.com">MFractor</a>
site_author: "Matthew Robbins"
site_description: "Documentation for MFractor for Mac, incredible Xamarin tools"
site_favicon: "img/favicon.ico"
repo_url: "https://github.com/matthewrdev/mfractor-documentation"
remote_branch: "master"
google_analytics: ['UA-71910290-3', 'docs.mfractor.com']
strict: true
theme_dir: theme
extra_css:
    - css/breadcrumbs.css
    - css/code.css
    - css/fabric.css
    - css/sidenav.css
    - css/mfractor.css

pages:
- Home: index.md
- Getting Started:
  - Setup: setup.md
  - Support: support.md
  - Xamarin.Forms Quickstart: xamarin-forms-quickstart.md
  - Xamarin.Android Quickstart: xamarin-android-quickstart.md
- Xamarin.Forms:
  - Configure Binding Context: xamarin-forms/configure-binding-context.md
  - Navigation: xamarin-forms/navigation.md
  - Analysis: xamarin-forms/analysis.md
  - Refactoring And Code Generation: xamarin-forms/refactoring-and-code-generation.md
  - Tools In-Depth:
    - Analysers: xamarin-forms/tools-in-depth/analysers.md
    - Refactorings: xamarin-forms/tools-in-depth/refactorings.md
- Xamarin.Android:
  - Project Resource Indexing: xamarin-android/project-resource-indexing.md
  - Navigation: xamarin-android/navigation.md
  - Analysis: xamarin-android/analysis.md
  - Refactoring And Code Generation: xamarin-android/refactoring-and-code-generation.md
  - .NET Code Analysis: xamarin-android/dotnet-code-analysis.md
  - Resource IntelliSense: xamarin-android/resource-intellisense.md
  - Tools In-Depth:
    - Analysers: xamarin-android/tools-in-depth/analysers.md
    - Refactorings: xamarin-android/tools-in-depth/refactorings.md
    - IntelliSense: xamarin-android/tools-in-depth/intellisense.md
- Tutorials:
  - Tutorials: tutorials/tutorials.md
  - Xamarin.Android:
    - Resource Expressions And Code Navigation: tutorials/xamarin-android/resource-expressions-and-code-navigation.md
  - Xamarin.Forms:
    - Mvvm Navigation: tutorials/xamarin-forms/mvvm-navigation.md
    - Implementing View Models: tutorials/xamarin-forms/implementing-view-models.md
    - Value Converter Type Safety: tutorials/xamarin-forms/value-converter-type-safety.md
- Release Notes:
    - 2.7: release-notes/v2-7.md
    - 2.6: release-notes/v2-6.md
    - 2.5: release-notes/v2-5.md
