site_name: mfractor docs
theme: readthedocs
copyright: Copyright &copy; 2016 <a href="https://www.mfractor.com">MFractor</a>
site_author: "Matthew Robbins"
site_description: "Documentation for MFractor for Mac, incredible Xamarin tools"
site_favicon: "img/favicon.ico"
repo_url: "https://github.com/mfractor/mfractor.github.io"
remote_branch: "master"
google_analytics: ['UA-71910290-3', 'docs.mfractor.com']
strict: true
theme_dir: theme
extra_css:
    - css/breadcrumbs.css
    - css/code.css
    - css/fabric.css
    - css/sidenav.css
    - css/mfractor.css

pages:
- Home: index.md
- Getting Started:
  - Setup: setup.md
  - FAQ: faq.md
  - Using Code Actions: code-actions.md
  - Configuration: configuration.md
  - Xamarin.Forms Quickstart: xamarin-forms-quickstart.md
  - Xamarin.Android Quickstart: xamarin-android-quickstart.md
- Xamarin.Forms:
  - Configure Binding Context: xamarin-forms/configure-binding-context.md
  - Navigation: xamarin-forms/navigation.md
  - Analysis: xamarin-forms/analysis.md
  - Implementing View Models: xamarin-forms/implementing-view-models.md
  - Value Converter Type Safety: xamarin-forms/value-converter-type-safety.md
- Xamarin.Android:
  - Resource Navigation: xamarin-android/resource-navigation.md
  - Analysis: xamarin-android/analysis.md
  - .NET Code Analysis: xamarin-android/dotnet-code-analysis.md
  - Resource IntelliSense: xamarin-android/resource-intellisense.md
- Release Notes:
    - v3.0: release-notes/v3-0.md
    - v2.10: release-notes/v2-10.md
    - v2.9: release-notes/v2-9.md
    - v2.8: release-notes/v2-8.md
    - v2.7: release-notes/v2-7.md
    - v2.6: release-notes/v2-6.md
    - v2.5: release-notes/v2-5.md
