site_name: MFractor Documentation
copyright: Copyright &copy; 2015-2020 <a href="https://www.mfractor.com">MFractor Pty Ltd</a>
site_author: "MFractor Pty Ltd"
site_description: "Documentation for MFractor, a powerful productivity tool for Xamarin developers"
repo_url: "https://github.com/mfractor/mfractor.github.io"
edit_uri: tree/docs/docs
remote_branch: "master"
google_analytics: ['UA-71910290-3', 'docs.mfractor.com']
strict: true
theme:
  name: 'material'
  logo: 'images/logo.svg'
  favicon: 'images/favicon.ico'
  palette:
    primary: 'blue'

extra:
  disqus: 'mfractor'

markdown_extensions:
  - attr_list
  - admonition
  - codehilite
  - meta
  - pymdownx.tabbed
  - pymdownx.superfences
  - pymdownx.mark

extra_css:
  - css/tabs.css
  - css/all.css

extra_javascript:
  - js/tabs.js
  - js/set-cookie.js
  - js/get-cookie.js

nav:
- Home: index.md
- General:
  - Support: support.md
  - Licensing: licensing.md
  - ReSharper Compatibility: resharper-compatibility.md
  - FAQ: faq.md
  - Contributing: contributing.md
- Feature Matrix: feature-matrix.md
- Installation And Setup: installation-and-setup.md
- Quickstart - Windows: quickstart-windows.md
- Quickstart - Mac: quickstart-mac.md
- Scaffolder: scaffolder.md
- Code Actions: code-actions.md
- Analysis:
  - Overview: analysis/overview.md
  - Disabling Analysers: analysis/disabling-analysers.md
- Image Management:
  - Overview: image-management/overview.md
  - Managing Images Assets: image-management/managing-image-assets.md
  - Importing Images: image-management/image-importer.md
  - Deleting Image Assets: image-management/deleting-image-assets.md
  - Optimising Image Assets: image-management/optimising-image-assets.md
  - Image Tooltips: image-management/image-tooltips.md
  - Third Party:
    - Mobile.BuildTools: image-management/third-party/mobile-build-tools.md
    - ResizetizerNT: image-management/third-party/resizetizer.md
- C#:
  - Create Class From Clipboard: csharp/create-class-from-clipboard.md
  - Code Actions:
    - Generate Interface Implementation: csharp/code-actions/generate-interface-implementation.md
    - Simplifying Qualified Types: csharp/code-actions/simplify-qualified-types.md
    - Locate In Solution Explorer: csharp/code-actions/locate-in-solution-explorer.md
    - Create Lazy Accessor: csharp/code-actions/create-lazy-accessor.md
    - Convert To Interpolated String: csharp/code-actions/convert-to-interpolated-string.md
    - Align Namespace To Folder Path: csharp/code-actions/align-namespace-to-folder-path.md
    - Invert Event Handler: csharp/code-actions/invert-event-handler.md
    - Generate ReadOnly Constructor: csharp/code-actions/generate-readonly-constructor.md
    - Select String Span: csharp/code-actions/select-string-span.md
    - Copy Var Type To Clipboard: csharp/code-actions/copy-var-type-to-clipboard.md
- Android:
  - Copy Package ID: android/tools/copy-package-id.md
  - Open Android Manifest: android/tools/open-android-manifest.md
- iOS:
  - Tools:
    - Copy Bundle ID: ios/tools/copy-bundle-id.md
- Xamarin.Forms:
  - Overview: xamarin-forms/overview.md
  - XAML Editor:
    - XAML IntelliSense: xamarin-forms/xaml-intellisense.md
  - Automatic Type Inference: xamarin-forms/automatic-type-inference.md
  - Analysis:
    - C# Newline Characters: xamarin-forms/analysis/invalid-newline-characters.md
    - Code Behind Fields: xamarin-forms/analysis/code-behind-fields.md
    - Thickness: xamarin-forms/analysis/thickness.md
    - CollectionView: xamarin-forms/analysis/collection-view.md
    - Slider: xamarin-forms/analysis/slider.md
  - Binding Context Resolution:
    - Overview: xamarin-forms/binding-context-resolution/overview.md
    - Automatic ViewModel Detection: xamarin-forms/binding-context-resolution/automatic-viewmodel-detection.md
    - BindingContext Evaluation: xamarin-forms/binding-context-resolution/binding-context-evaluation.md
    - DataTemplate Binding Context Resolution: xamarin-forms/binding-context-resolution/data-template-binding-context-resolution.md
    - Using The DesignTimeBindingContextAttribute: xamarin-forms/binding-context-resolution/design-time-binding-context-attribute.md
    - Cross Project Binding Context Resolution: xamarin-forms/binding-context-resolution/cross-project-binding-context-resolution.md
  - Working With ViewModels:
    - View-ViewModel Navigation: xamarin-forms/working-with-viewmodels/view-viewmodel-navigation.md
    - Data Binding IntelliSense: xamarin-forms/working-with-viewmodels/data-binding-intellisense.md
    - Data Binding Analysis: xamarin-forms/working-with-viewmodels/data-binding-analysis.md
    - Generating Properties/Commands: xamarin-forms/working-with-viewmodels/generating-properties-and-commands.md
    - MVVM Wizard: xamarin-forms/working-with-viewmodels/mvvm-wizard.md
  - Working with Styles:
    - Extracting Styles: xamarin-forms/working-with-styles/extracting-styles.md
    - Matching Style Analysis: xamarin-forms/working-with-styles/matching-style-analysis.md
    - Analysis: xamarin-forms/working-with-styles/analysis.md
  - Custom Controls:
    - Extracting Custom Controls: xamarin-forms/custom-controls/extracting-custom-controls.md
    - Bindable Property Wizard: xamarin-forms/custom-controls/bindable-property-wizard.md
    - Attached Property Wizard: xamarin-forms/custom-controls/attached-property-wizard.md
  - Custom Renderers:
    - Generate Custom Renderers: xamarin-forms/custom-renderers/generate-custom-renderers.md
    - Find Custom Renderers: xamarin-forms/custom-renderers/find-custom-renderers.md
  - Value Converters:
    - Value Converter Wizard: xamarin-forms/value-converters/value-converter-wizard.md
  - Grids:
    - Grid Intellisense Commands: xamarin-forms/grids/intellisense.md
    - Grid Analysis: xamarin-forms/grids/analysis.md
    - Convert StackLayout to Grid: xamarin-forms/grids/convert-stacklayout-to-grid.md
    - Tooltips: xamarin-forms/grids/tooltips.md
    - Adornments: xamarin-forms/grids/adornments.md
    - Shorthand Declaration Refactorings: xamarin-forms/grids/shorthand-declaration-refactorings.md
    - Insert Grid Row/Column: xamarin-forms/grids/insert-row-columns.md
    - Delete Grid Row/Column: xamarin-forms/grids/delete-row-columns.md
  - Static Resources:
    - Refactoring: xamarin-forms/static-resources/refactoring.md
    - Tooltips: xamarin-forms/static-resources/tooltips.md
    - Analysis: xamarin-forms/static-resources/analysis.md
  #- Dynamic Resources:
  #  - Navigation: xamarin-forms/dynamic-resources/navigation.md
  #  - Intellisense Completions: xamarin-forms/dynamic-resources/intellisense.md
  #  - Global Search Capabilities: xamarin-forms/dynamic-resources/search.md
  #  - Tooltips: xamarin-forms/dynamic-resources/tooltips.md
  - Colors:
    - Adornments: xamarin-forms/colors/adornments.md
    - Color Analysis: xamarin-forms/colors/color-analysis.md
    - Color Code Actions: xamarin-forms/colors/code-actions.md
  - Fonts:
    - FontFamily Resolution: xamarin-forms/fonts/font-family-resolution.md
    - Tooltips: xamarin-forms/fonts/tooltips.md
    - Code Completion: xamarin-forms/fonts/code-completion.md
    - Analysis: xamarin-forms/fonts/analysis.md
  - Thicknesses:
    - Thickness Analysis: xamarin-forms/thicknesses/analysis.md
    - Consolidate: xamarin-forms/thicknesses/consolidation.md
    - Validate and Simplify: xamarin-forms/thicknesses/invalid-thickness.md
  - Images:
    - Analysis: xamarin-forms/images/analysis.md
    - Code Completion: xamarin-forms/images/code-completion.md
    - Replace With IconImageSource: xamarin-forms/images/replace-with-icon-image-source.md
- Fonts:
  - Importing Fonts: fonts/importing-fonts.md
  - Generate Font Glyph Code Class: fonts/generate-font-character-code-class.md
  - UIAppFonts Entry: fonts/uiappfonts-plist-entry.md
  - FontFamily XAML Entry: fonts/fontfamily-xaml-entry.md
- Utilities:
  - Delete Output Folders: utilities/delete-output-folders.md
  - Clean And Compress: utilities/clean-and-compress.md
  - Edit Shared Project Items: utilities/edit-shared-project-items.md
  - Copy Resource ID To Clipboard: utilities/copy-resource-id-to-clipboard.md
  - Resync Solution Resources: utilities/resync-mfractor-resources.md
- Release Notes:
  - Mac:
    - Current Release: release-notes/mac/current.md
    - v4:
      - v4.3: release-notes/mac/v4/v4.3.md
      - v4.2: release-notes/mac/v4/v4.2.md
      - v4.1: release-notes/mac/v4/v4.1.md
      - v4.0: release-notes/mac/v4/v4.0.md
    - v3:
      - v3.10: release-notes/mac/v3/v3.10.md
      - v3.9: release-notes/mac/v3/v3.9.md
  - Windows:
    - Current Release: release-notes/windows/current.md
    - v4:
      - v4.3: release-notes/windows/v4/v4.3.md
      - v4.2: release-notes/windows/v4/v4.2.md
      - v4.1: release-notes/windows/v4/v4.1.md
      - v4.0: release-notes/windows/v4/v4.0.md
    - v0:
      - v0.6: release-notes/windows/v0/v0.6.md
      - v0.5: release-notes/windows/v0/v0.5.md
      - v0.4: release-notes/windows/v0/v0.4.md
      - v0.3: release-notes/windows/v0/v0.3.md
      - v0.2: release-notes/windows/v0/v0.2.md
      - v0.1: release-notes/windows/v0/v0.1.md
- Legal:
  - Third Party Software: legal/third-party-software.md
  - Privacy Policy: legal/privacy-policy.pdf
  - End User License: legal/end-user-license.pdf
