site_name: mfractor docs
theme: readthedocs
copyright: Copyright &copy; 2016 <a href="https://www.mfractor.com">MFractor</a>
site_author: "Matthew Robbins"
site_description: "Documentation for MFractor for Mac, incredible Xamarin tools"
site_favicon: "img/favicon.ico"
repo_url: "https://github.com/mfractor/mfractor.github.io"
remote_branch: "master"
google_analytics: ['UA-71910290-3', 'docs.mfractor.com']
strict: true
theme_dir: theme
extra_css:
    - css/breadcrumbs.css
    - css/code.css
    - css/fabric.css
    - css/sidenav.css
    - css/mfractor.css

pages:
- Home: index.md
- Getting Started:
  - Installation And Setup: installation-and-setup.md
  - About MFractor Professional: mfractor-professional.md
  - Code Actions: code-actions.md
  - Image Importing Wizard: image-importing-wizard.md
  - Localisation Wizard: localisation-wizard.md
  - Using MFractor.Annotations: annotations.md
- Configuring MFractor:
  - Getting Started: configuration/getting-started.md
  - Configurable Items: configuration/configurable-items.md
  - Code Snippets: configuration/code-snippets.md
  - Types: configuration/configuration-property-types.md
  - ResX: configuration/resx.md
  - Xamarin.Forms: configuration/xamarin-forms.md
- Xamarin.Forms:
  - Configuring A Binding Context: xamarin-forms/configure-binding-context.md
  - Navigation Tools: xamarin-forms/navigation.md
  - Analysis: xamarin-forms/analysis.md
  - Implementing View Models: xamarin-forms/implementing-view-models.md
  - Value Converter Type Safety: xamarin-forms/value-converter-type-safety.md
- Code Actions:
  - C#:
    - C# Code Actions: code-actions/csharp.md
    - Android: code-actions/csharp/android.md
    - Xamarin.Forms: code-actions/csharp/forms.md
  - Xamarin.Forms Xaml Code Actions:
    - Issue Fixing: code-actions/xaml/fix.md
    - Code Generation: code-actions/xaml/generate.md
    - Xaml Organisation: code-actions/xaml/organise.md
    - Refactoring: code-actions/xaml/refactor.md
    - Navigation: code-actions/xaml/navigate.md
  - XML Code Actions: code-actions/xml.md
- Code Analysis:
  - C#:
    - Android C# Analysis: code-analysis/csharp/android.md
    - Xamarin.Forms C# Analysis: code-analysis/csharp/xamarin-forms.md
  - XAML Analysis: code-analysis/xaml.md
  - MFractor Configuration Analysis: code-analysis/configuration.md
- Code Generation:
  - C#:
    - C#: code-generation/csharp.md
  - Android (C#):  code-generation/csharp/android.md
  - Xamarin.Forms (C#): code-generation/xamarin-forms.md
  - Linker: code-generation/linker.md
  - Xaml: code-generation/xaml.md
  - ResX: code-generation/resx.md
  - XML: code-generation/xml.md
- Code Completion:
  - XAML IntelliSense: code-completion/xaml.md
- Localisation:
  - Localisation: localisation.md
  - Translation: translation.md
- Misc:
  - Search: search.md
  - Utilities: utilities.md
  - Debugging: debugging.md
- Release Notes:
    - v3.5: release-notes/v3-5.md
    - v3.4: release-notes/v3-4.md
    - v3.3: release-notes/v3-3.md
    - v3.2: release-notes/v3-2.md
    - v3.1: release-notes/v3-1.md
    - v3.0: release-notes/v3-0.md
    - v2: release-notes/v2.md
